public class Main {
    public static void main(String[] args) {
        System.out.println("Исходные данные для трех задач");
        System.out.println("Задача номер №1");
        var dog = 8.0;
        System.out.println(dog);
        var cat = 3.6;
        System.out.println(cat);
        var paper = 763789;
        System.out.println(paper);
        System.out.println();
        System.out.println("Задача номер №2");
        var resultAddDog = dog + 4;
        System.out.println(resultAddDog);
        var resultAddCat = cat + 4;
        System.out.println(resultAddCat);
        var resultAddPaper = paper + 4;
        System.out.println(resultAddPaper);
        System.out.println();
        System.out.println("Задача номер №3");
        var resultTakeAwayDog = dog - 3.5;
        System.out.println(resultTakeAwayDog);
        var resultTakeAwayCat = cat - 1.6;
        System.out.println(resultTakeAwayCat);
        var resultTakeAwayPaper = paper - 7639;
        System.out.println(resultTakeAwayPaper);
        System.out.println();
        System.out.println("Задача номер №4");
        var friend = 19;
        System.out.println(friend);
        var addFriend = friend + 2;
        System.out.println(addFriend);
        var shareFriend = addFriend / 7;
        System.out.println(shareFriend);
        System.out.println();
        System.out.println("Задача номер №5");
        var frog = 3.5;
        System.out.println(frog);
        var multiplyFrog = frog * 10;
        System.out.println(multiplyFrog);
        var shareFrog = multiplyFrog / 3.5;
        System.out.println(shareFrog);
        var addFrog = shareFrog + 4;
        System.out.println(addFrog);
        System.out.println();
        System.out.println("Задача номер №6 'Масса боксеров'");
        var boxerFirstWeight = 78.2;
        System.out.println("Масса первого боксера " + boxerFirstWeight+ " кг,");
        var boxerSecondWeight = 82.7;
        System.out.println("Масса второго боксера " + boxerSecondWeight+ " кг.");
        var boxerAddWeight = boxerFirstWeight + boxerSecondWeight;
        System.out.println("Общая масса боксеров " + boxerAddWeight+ " кг");
        var boxerResidueWeight = boxerSecondWeight - boxerFirstWeight;
        System.out.println("разница в весе боксеров " + boxerResidueWeight+ " кг.");
        System.out.println();
        System.out.println("Задача номер №7 (Разница в весе через остаток от деления)");
        var athleteFerstWeight =(boxerSecondWeight% boxerFirstWeight);
        System.out.println("Разница в весе спортсменов " + athleteFerstWeight+ " кг.");
        System.out.println();
        System.out.println("Задача номер №8");
        var overallTime = 640;
        var timePerson = 8;
        var numberOfPersonnel = overallTime / timePerson;
        System.out.println("Всего работников в компании — " + numberOfPersonnel+ " человек.");
        var addNumberOfPersonnel = numberOfPersonnel + 94;
        var newOverallTime = addNumberOfPersonnel * timePerson;
        System.out.println("Если в компании работает " + addNumberOfPersonnel+ " человека, то всего " + newOverallTime+ " часа работы может быть поделено между сотрудниками");
    }
}